name: robustness
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - decorator=4.4.1=py_0
  - ffmpeg=4.2=h167e202_0
  - freetype=2.10.1=he06d7ca_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - intel-openmp=2020.0=166
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1006
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - nettle=3.4.1=h1bed415_1002
  - numpy-base=1.18.1=py36hde5b4d6_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.1=py36h0573a6f_0
  - pip=20.0.2=py36_1
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - readline=7.0=h7b6447c_5
  - scipy=1.4.1=py36h0b6359f_0
  - setuptools=45.2.0=py36_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - bezier==2020.5.19
    - bokeh==2.0.2
    - click==7.1.2
    - cloudpickle==1.4.1
    - colorcet==2.0.2
    - contextvars==2.4
    - dask==2.16.0
    - datashader==0.10.0
    - datashape==0.5.2
    - distributed==2.16.0
    - dynetx==0.2.2
    - eon==1.1
    - fa2==0.3.5
    - ffmpeg==4.2.2
    - fsspec==0.7.4
    - future==0.18.2
    - heapdict==1.0.1
    - idna==2.9
    - immutables==0.14
    - importlib-metadata==1.6.0
    - jinja2==2.11.2
    - kiwisolver==1.1.0
    - llvmlite==0.32.1
    - locket==0.2.0
    - markupsafe==1.1.1
    - matplotlib==3.1.3
    - msgpack==1.0.0
    - multipledispatch==0.6.0
    - ndlib==5.0.0
    - netdispatch==0.0.5
    - numba==0.49.1
    - numpy==1.18.1
    - packaging==20.3
    - param==1.9.3
    - partd==1.1.0
    - pebble==4.5.1
    - pillow==7.1.2
    - pluggy==0.13.1
    - prettytable==0.7.2
    - psutil==5.7.0
    - pyct==0.4.6
    - pyparsing==2.4.6
    - pytest==5.4.2
    - python-igraph==0.8.2
    - pyyaml==5.3.1
    - requests==2.23.0
    - sortedcontainers==2.1.0
    - stopit==1.1.2
    - tblib==1.6.0
    - texttable==1.6.2
    - toolz==0.10.0
    - tqdm==4.43.0
    - typing-extensions==3.7.4.2
    - urllib3==1.25.9
    - xarray==0.15.1
    - zict==2.0.0
    - zipp==3.1.0

